export default function CashAccelerationSVG() {
  return (
    <div>
      <svg
        width="330"
        height="330"
        xmlns="http://www.w3.org/2000/svg"
        className="z-0"
      >
        <ellipse
          cx="0"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="0"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="22"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="44"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="66"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="88"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="110"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="132"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="154"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="176"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="198"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="220"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="242"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="264"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="286"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="0"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="22"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="44"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="66"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="88"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="110"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="132"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="154"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="176"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="198"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="220"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="242"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="264"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="286"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
        <ellipse
          cx="308"
          cy="308"
          rx="3"
          ry="2.55"
          fill="#F68ABB"
          fill-opacity="0.7"
        ></ellipse>
      </svg>
    </div>
  );
}
